const dicoPermissions = {
    "AddReactions": "Ajouter des réactions",
    "Administrator": "Administrateur",
    "AttachFiles": "Joindre des fichiers",
    "BanMembers": "Bannir des membres",
    "ChangeNickname": "Changer les pseudos",
    "Connect": "Se connecter",
    "CreateInstantInvite": "Créer une invitation",
    "CreatePrivateThreads": "Créer des fils privés",
    "CreatePublicThreads": "Créer des fils publics",
    "DeafenMembers": "Mettre en sourdine des membres",
    "EmbedLinks": "Intégrer des liens",
    "KickMembers": "Expulser des membres",
    "ManageChannels": "Gérer les salons",
    "ManageEmojisAndStickers": "Gérer les émojis et les autocollants",
    "ManageEvents": "Gérer les événements",
    "ManageGuild": "Gérer le serveur",
    "ManageMessages": "Gérer les messages",
    "ManageNicknames": "Gérer les pseudos",
    "ManageRoles": "Gérer les rôles",
    "ManageThreads": "Gérer les fils",
    "ManageWebhooks": "Gérer les webhooks",
    "MentionEveryone": "Mentionner @everyone, @here et tous les rôles",
    "ModerateMembers": "Exclure temporairement des membres",
    "MoveMembers": "Déplacer des membres",
    "MuteMembers": "Rendre les membres muets",
    "PrioritySpeaker": "Voix prioritaire",
    "ReadMessageHistory": "Voir les anciens messages",
    "RequestToSpeakmessages": "Demande de prise de parole",
    "SendMessages": "Envoyer des messages",
    "SendMessagesInThreads": "Envoyer des messages dans les fils",
    "SendTtsMessages": "Envoyer des messages de synthèse vocale",
    "Speak": "Parler",
    "Stream": "Vidéo",
    "UseApplicationCommands": "Utiliser les commandes de l'application",
    "UseEmbeddedActivities": "Utiliser les Activités",
    "UseExternalEmojis": "Utiliser des émojis externes",
    "UseExternalStickers": "Utiliser des autocollants externes",
    "UsePrivateThreads": "Utiliser les fils privés",
    "UsePublicThreads": "Utiliser les fils publics",
    "UseVad": "Utiliser la Détection de la voix",
    "ViewAuditLog": "Voir les logs du serveurs",
    "ViewChannel": "Voir les salons",
    "ViewGuildInsights": "Voir les stats du serveur"
}

module.exports = {
    dicoPermissions
}